name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run_workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: mochajs Testing Workflow
        uses: ./.github/workflows/mochajs.yml

      - name: SonarCloud Workflow
        uses: ./.github/workflows/sonarcloud.yml

      - name: nodejs Workflow
        uses: ./.github/workflows/nodejs.yml

      - name: Netlify Deployment Workflow
        uses: ./.github/workflows/netlify.yml
