name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your desired branch

jobs:
  build_test_analyze_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Adjust to your desired Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Install Mocha
        run: npm install mocha -g

      - name: Run Tests with Mocha
        run: mocha test/test.js # Adjust to your test command (Mocha)

      - name: Run SonarCloud Analysis
        uses: sonarsource/sonarcloud-github-action@master
        with:
          projectBaseDir: . #adjust accordingly
          args: >
              -Dsonar.projectKey=jabircode_DV1C02-Code-Management-CWF
              -Dsonar.organization=$SONAR_ORG
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORG: ${{ secrets.ORGANIZATION }} # Replace with your SonarCloud organization key

      - name: Build Project
        run: npm run build # Replace with your build command

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: ./build # Adjust to your build output directory
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
